# Generated by Django 6.0 on 2025-12-06 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название коллекции')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание коллекции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование медиафайла')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание медиафайла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('file', models.FileField(upload_to='media_items/', verbose_name='Файл медиа')),
                ('media_type', models.IntegerField(choices=[(1, 'image'), (2, 'video'), (3, 'audio')], verbose_name='Тип медиа')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тега')),
                ('media_item', models.ManyToManyField(blank=True, related_name='tags', to='core.mediaitem', verbose_name='Медиафайлы')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='MediaLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время лайка')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediaitem', verbose_name='Медиафайл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк медиафайла',
                'verbose_name_plural': 'Лайки медиафайлов',
                'db_table': 'media_like',
            },
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Владелец медиафайла'),
        ),
        migrations.CreateModel(
            name='MediaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('commented_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время комментария')),
                ('media_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mediaitem', verbose_name='Медиафайл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к медиафайлу',
                'verbose_name_plural': 'Комментарии к медиафайлам',
                'db_table': 'media_comment',
            },
        ),
    ]
