# Generated by Django 6.0 on 2025-12-09 09:05

import django.utils.timezone
from django.db import migrations, models


def copy_created_to_updated(apps, schema_editor):
    Model = apps.get_model('core', 'MediaItem')
    Model.objects.update(updated_at=models.F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время изменения'),
            preserve_default=False,
        ),
        migrations.RunPython(copy_created_to_updated)
    ]
