# Generated by Django 6.0 on 2026-08-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mediaitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения'),
        ),
    ]
